---
version: "3"

services:
  # This service runs the Vault server in dev mode. This means that data is not
  # persisted between restarts (good to keep in mind).
  # The Vault UI will be accessible at http://localhost:8200/ui
  vault:
    image: vault:latest
    command: server -dev
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_TOKEN=root
      - VAULT_UI=true
    volumes:
      - ./vault/config:/vault/config
    ports:
      - 8200:8200
